path: delta # can use any spark path, local, s3a, gcp, blob, dbfs, hdfs, etc

weather:
  api_key: 39e5033200dafe4ec95afa2b7972db6f
  endpoint: https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={key}&units=metric
  folder_name: weather
cities:
  manaus:
    lat: -3.1170
    long: -60.0258
  brasilia:
    lat: -15.7939
    long: -47.8828
  rio_de_janeiro:
    lat: -22.9083
    long: -43.1964
  sao_paulo:
    lat: -23.5340
    long: -46.6289
  recife:
    lat: -8.0500
    long: -34.9000
  salvador:
    lat: -12.9747
    long: -38.4767
  goiania:
    lat: -16.6651
    long: -49.2860
  belo_horizonte:
    lat: -19.9130
    long: -43.9409
  curitiba:
    lat: -25.4411
    long: -49.2769
  florianopolis:
    lat: -27.5935
    long: -48.5585

